In [1]:
print("hello world")

hello world

In [ ]:
%pip install numpy pandas matplotlib seaborn

In [4]:
%pip install numpy pandas matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Collecting numpy
  Using cached numpy-2.4.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting pandas
  Using cached pandas-2.3.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting matplotlib
  Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\salfil\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\salfil\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\salfil\appdata\roaming\python\python313\site-packages (from pandas) (2025.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.61.1-cp313-cp313-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\salfil\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\salfil\appdata\roaming\python\python313\site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\salfil\appdata\roaming\python\python313\site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: six>=1.5 in c:\users\salfil\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached numpy-2.4.1-cp313-cp313-win_amd64.whl (12.3 MB)
Using cached pandas-2.3.3-cp313-cp313-win_amd64.whl (11.0 MB)
Using cached matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp313-cp313-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Installing collected packages: numpy, kiwisolver, fonttools, cycler, pandas, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------------------------------------- 0/8 [numpy]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   ---------- ----------------------------- 2/8 [fonttools]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   -------------------- ------------------- 4/8 [pandas]
   ------------------------- -------------- 5/8 [contourpy]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 kiwisolver-1.4.9 matplotlib-3.10.8 numpy-2.4.1 pandas-2.3.3 seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\Salfil\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\Salfil\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import sys
sys.executable

'C:\\Python313\\python.exe'

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("All imports successful")

All imports successful

In [7]:
df = pd.read_csv("data/customer_signups.csv")

df.head()

,customer_id,name,email,signup_date,source,region,plan_selected,marketing_opt_in,age,gender
0,CUST00000,Joshua Bryant,NaN,NaN,Instagram,NaN,basic,No,34,Female
1,CUST00001,Nicole Stewart,nicole1@example.com,02-01-24,LinkedIn,West,basic,Yes,29,Male
2,CUST00002,Rachel Allen,rachel2@example.com,03-01-24,Google,North,PREMIUM,Yes,34,Non-Binary
3,CUST00003,Zachary Sanchez,zachary3@mailhub.org,04-01-24,YouTube,NaN,Pro,No,40,Male
4,CUST00004,NaN,matthew4@mailhub.org,05-01-24,LinkedIn,West,Premium,No,25,Other

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       298 non-null    object
 1   name              291 non-null    object
 2   email             266 non-null    object
 3   signup_date       298 non-null    object
 4   source            291 non-null    object
 5   region            270 non-null    object
 6   plan_selected     292 non-null    object
 7   marketing_opt_in  290 non-null    object
 8   age               288 non-null    object
 9   gender            292 non-null    object
dtypes: object(10)
memory usage: 23.6+ KB

In [9]:
df.isna().sum()

customer_id          2
name                 9
email               34
signup_date          2
source               9
region              30
plan_selected        8
marketing_opt_in    10
age                 12
gender               8
dtype: int64

In [10]:
df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')

C:\Users\Salfil\AppData\Local\Temp\ipykernel_28356\4275275286.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')

In [11]:
df['signup_date'].dtype

dtype('<M8[ns]')

In [12]:
df['signup_date'] = pd.to_datetime(
    df['signup_date'],
    format='%Y-%m-%d',
    errors='coerce'
)

In [13]:
df['signup_date'].dtype

dtype('<M8[ns]')

In [14]:
df['plan_selected'] = (
    df['plan_selected']
    .str.strip()
    .str.lower()
    .str.capitalize()
)

In [15]:
df['gender'] = (
    df['gender']
    .str.strip()
    .str.lower()
    .str.capitalize()
)

In [16]:
#check to see if cleaning for 'gender' and 'plan_selected' worked
df['plan_selected'].value_counts(dropna=False)
df['gender'].value_counts(dropna=False)

gender
Female        93
Male          92
Other         59
Non-binary    42
NaN            8
123            6
Name: count, dtype: int64

In [17]:
#check duplicates
duplicate_count = df.duplicated(subset='customer_id').sum()
duplicate_count

np.int64(1)

In [18]:
#duplicate customer IDs before
duplicate_count = df.duplicated(subset='customer_id').sum()
print(duplicate_count)

1

In [19]:
df = df.drop_duplicates(subset='customer_id')

In [20]:
#Check duplicate CustomerIDs after
duplicate_count = df.duplicated(subset='customer_id').sum()
print(duplicate_count)

0

In [21]:
#fill missing regions with Unknown
df['region'] = df['region'].fillna("Unknown")

In [22]:
df['email'] = df['email'].fillna("Unknown")

In [23]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [24]:
df['age_missing_flag'] = df['age'].isna()

In [25]:
df['age_missing_flag'].sum()

np.int64(19)

In [26]:
#check how many are missing an age
print(df['age_missing_flag'].sum())

19

In [32]:
#Count of missing values per column
missing_count=df.isna().sum()
print(missing_count)

customer_id          1
name                 9
email                0
signup_date          6
source               9
region               0
plan_selected        8
marketing_opt_in    10
age                 19
gender               8
age_missing_flag     0
dtype: int64

In [29]:
#percentage of missing values
missing_percentage = (df.isna().mean() * 100).round(2)
missing_percentage

customer_id         0.33
name                3.01
email               0.00
signup_date         2.01
source              3.01
region              0.00
plan_selected       2.68
marketing_opt_in    3.34
age                 6.35
gender              2.68
age_missing_flag    0.00
dtype: float64

In [30]:
duplicate_count

np.int64(0)

In [31]:
print(duplicate_count)

0

In [34]:
#table showing missing counts and percentages
data_quality_summary = pd.DataFrame({
    'Missing Count': missing_count,
    'Missing %': missing_percentage
})

data_quality_summary

                  Missing Count  Missing %
customer_id                   1       0.33
name                          9       3.01
email                         0       0.00
signup_date                   6       2.01
source                        9       3.01
region                        0       0.00
plan_selected                 8       2.68
marketing_opt_in             10       3.34
age                          19       6.35
gender                        8       2.68
age_missing_flag              0       0.00

In [35]:
#inconsistent Categories Corrected
df['plan_selected'].value_counts(dropna=False)

plan_selected
Premium        99
Pro            94
Basic          92
NaN             8
Unknownplan     6
Name: count, dtype: int64

In [36]:
df['gender'].value_counts(dropna=False)

gender
Female        92
Male          92
Other         59
Non-binary    42
NaN            8
123            6
Name: count, dtype: int64

In [39]:
signups_per_week = (
    df
    .set_index('signup_date')
    .resample('W')
    .size()
    .reset_index(name='signups')
)

signups_per_week.head()

  signup_date  signups
0  2024-01-07        6
1  2024-01-14        5
2  2024-01-21        7
3  2024-01-28        7
4  2024-02-04        8

In [40]:
#sign ups by source
signups_by_source = df['source'].value_counts().reset_index()
signups_by_source.columns = ['source', 'signups']
signups_by_source.head()

      source  signups
0    YouTube       58
1     Google       50
2   Referral       49
3  Instagram       48
4   Facebook       40

In [41]:
signups_by_region = df['region'].value_counts().reset_index()
signups_by_region.columns = ['region', 'signups']

In [42]:
signups_by_region.head()

    region  signups
0    North       65
1     East       61
2    South       59
3     West       45
4  Central       39

In [43]:
signups_by_plan = df['plan_selected'].value_counts().reset_index()
signups_by_plan.columns = ['plan_selected', 'signups']
signups_by_plan.head()

  plan_selected  signups
0       Premium       99
1           Pro       94
2         Basic       92
3   Unknownplan        6

In [44]:
marketing_by_gender = (
    df
    .groupby(['gender', 'marketing_opt_in'])
    .size()
    .reset_index(name='count')
)

marketing_by_gender

        gender marketing_opt_in  count
0          123               No      3
1          123              Yes      3
2       Female               No     47
3       Female              Yes     44
4         Male              Nil      1
5         Male               No     50
6         Male              Yes     38
7   Non-binary               No     20
8   Non-binary              Yes     19
9        Other               No     32
10       Other              Yes     24

In [45]:
age_summary = df['age'].agg(
    min_age='min',
    max_age='max',
    mean_age='mean',
    median_age='median',
    null_count=lambda x: x.isna().sum()
)

age_summary

min_age        21.000
max_age       206.000
mean_age       36.175
median_age     34.000
null_count     19.000
Name: age, dtype: float64

In [46]:
# which source bought in the most users last month
last_month = df['signup_date'].max().to_period('M') - 1

last_month_signups = df[
    df['signup_date'].dt.to_period('M') == last_month
]

last_month_signups['source'].value_counts()

source
Google       3
Instagram    2
Referral     1
Facebook     1
LinkedIn     1
Name: count, dtype: int64

In [47]:
# which region shows signs of missing or incomplete data:

df['region'].value_counts(dropna=False)

region
North      65
East       61
South      59
West       45
Central    39
Unknown    30
Name: count, dtype: int64

In [55]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[0, 24, 34, 44, 54, 100],
    labels=['<25', '25–34', '35–44', '45–54', '55+']
)

marketing_by_age = (
    df
    .groupby('age_group')['marketing_opt_in']
    .value_counts(normalize=True)
    .mul(100)
    .rename('percentage')
    .reset_index()
)

marketing_by_age

C:\Users\Salfil\AppData\Local\Temp\ipykernel_28356\4199040546.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby('age_group')['marketing_opt_in']

  age_group marketing_opt_in  percentage
0       <25               No   64.285714
1       <25              Yes   35.714286
2     25–34               No   54.961832
3     25–34              Yes   45.038168
4     35–44               No   51.020408
5     35–44              Yes   48.979592
6     45–54               No   51.063830
7     45–54              Yes   48.936170
8       55+               No   57.142857
9       55+              Yes   42.857143

In [49]:
plan_by_age = (
    df
    .groupby(['plan_selected', 'age_group'])
    .size()
    .reset_index(name='count')
)

plan_by_age

C:\Users\Salfil\AppData\Local\Temp\ipykernel_28356\2504792116.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(['plan_selected', 'age_group'])

   plan_selected age_group  count
0          Basic       <25      9
1          Basic     25–34     42
2          Basic     35–44     11
3          Basic     45–54     14
4          Basic       55+      5
5        Premium       <25      6
6        Premium     25–34     47
7        Premium     35–44     23
8        Premium     45–54     15
9        Premium       55+      4
10           Pro       <25     12
11           Pro     25–34     43
12           Pro     35–44     13
13           Pro     45–54     17
14           Pro       55+      4
15   Unknownplan       <25      0
16   Unknownplan     25–34      2
17   Unknownplan     35–44      2
18   Unknownplan     45–54      2
19   Unknownplan       55+      0

In [50]:
plan_by_age.pivot(
    index='plan_selected',
    columns='age_group',
    values='count'
).fillna(0)

age_group      <25  25–34  35–44  45–54  55+
plan_selected
Basic            9     42     11     14    5
Premium          6     47     23     15    4
Pro             12     43     13     17    4
Unknownplan      0      2      2      2    0

In [51]:
#getting rid of 'Nil' for marketing opt in

In [52]:
df['marketing_opt_in'].value_counts(dropna=False)

marketing_opt_in
No     156
Yes    132
NaN     10
Nil      1
Name: count, dtype: int64

In [53]:
df['marketing_opt_in'] = (
    df['marketing_opt_in']
    .str.strip()
    .str.capitalize()
    .replace({'Nil': 'No'})
)

In [54]:
df['marketing_opt_in'].value_counts(dropna=False)

marketing_opt_in
No     157
Yes    132
NaN     10
Name: count, dtype: int64

In [ ]:
#Marketing opt in count by gender